config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'index', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new', as: :new_task
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'
  get 'tasks/:id', to: 'tasks#show', as: :task
  delete 'tasks/:id', to: 'tasks#destroy', as: :destroy_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>
<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<div class="container">
  <h1>Tasks</h1>
  <% @tasks.each do |task| %>
    <ul class="list-group">
      <li class="list-group">
        <div class="d-flex">
          <%if task.completed == true %>
            <input class="form-check-input me-1" type="checkbox" value="" aria-label="..." checked>
          <% else %>
            <input class="form-check-input me-1" type="checkbox" value="" aria-label="...">
          <% end %>
          <%= link_to task.title, task_path(task) %>
          <%= link_to ">>delete task", destroy_task_path(task), data: {turbo_method: :delete, turbo_confirm: "estas seguro que deseas eliminar esta tarea?"} %>
        </div>
      </li>
    </ul>
  <% end %>
  <%= link_to ">>new task", new_task_path %>
</div>

app/views/tasks/new.html.erb
<h1>New task</h1>
<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<div class="container">
  <h1><%= @task.title %></h1>
  <p><%= @task.details %></p>
  <div class="d-flex">
    <p>is it done?</p>
    <%if @task.completed == true %>
      <input class="form-check-input me-1" type="checkbox" value="" aria-label="..." checked>
    <% else %>
      <input class="form-check-input me-1" type="checkbox" value="" aria-label="...">
    <% end %>
  </div>
  <%= link_to "Back to tasks", index_path %>
  <%= link_to ">>edit task", edit_task_path %>
</div>